<#
    SCCMAppHelper - the inventory, and the actions taken from it

    Three things exist per application, and the tool's job is to keep them in
    step and to say which of them are there:

        the definition   a row in Apps.csv - name, version, detection, commands
        the package      "<Name> - <Version>\" on the source share, with PSADT
                         and the installer in Files\
        the application  in the ConfigMgr site, with content on the distribution
                         points and deployments to the collections

    Get-AppInventory joins the three into one row per application, and the main
    dialog shows nothing else. Every action - add, build, publish, retire - is
    taken from a row of that list, and what makes sense follows from the state
    of the row: a definition without a package is built, a package without an
    application is published, a published application whose source has changed
    since is published again.

    Adding an application is one step. The installer is fetched - from the
    winget manifests, or picked from disk - the record is confirmed in the
    editor, and the package is built with the installer already in Files\. The
    row appears in the list as "ready, not published"; publishing is a second,
    deliberate click.
#>

#region ------------------------------------------------------------ inventory

<#
    The package folders on the source share: every folder below the work root
    holding a PSADT script. Nothing is asked of the site here.
#>
function Get-AppPackage {
    param($Config = (Get-ActiveConfig))

    $workRoot = Get-PackageWorkRoot -Config $Config
    $results  = @()

    foreach ($dir in (Get-ChildItem -LiteralPath $workRoot -Directory -ErrorAction SilentlyContinue)) {
        $contentPath = Get-PackageContentPath -PackageRoot $dir.FullName -Config $Config
        $adtScript   = Join-Path $contentPath 'Invoke-AppDeployToolkit.ps1'
        if (-not (Test-Path -LiteralPath $adtScript)) { continue }

        $parsed = Split-AppFolderName -FolderName $dir.Name

        # What Files\ holds decides whether the package can install anything.
        # Only the count is needed, so only metadata is read.
        $filesPath  = Join-Path $contentPath 'Files'
        $filesCount = 0
        if (Test-Path -LiteralPath $filesPath) {
            try { $filesCount = @([System.IO.Directory]::EnumerateFiles($filesPath, '*', [System.IO.SearchOption]::AllDirectories)).Count }
            catch { }
        }

        $results += [pscustomobject]@{
            AppName      = $parsed.Name
            AppVersion   = $parsed.Version
            PackageRoot  = $dir.FullName
            ContentPath  = $contentPath
            FilesCount   = $filesCount
            LastModified = (Get-Item -LiteralPath $adtScript).LastWriteTime
        }
    }

    return ($results | Sort-Object AppName, AppVersion)
}

<#
    What the site knows, keyed by application name. Read in three calls rather
    than three per application: every application with its package XML, every
    application deployment, and the distribution status of every package.

    The deployment type comment carries the tool signature and the content
    fingerprint, and both sit in the package XML - so the application object is
    enough to say whether this tool published it and whether the source has
    changed since (see Get-ContentFingerprint).
#>
function Get-CMApplicationState {
    param($Config = (Get-ActiveConfig))

    $signature = Get-ToolSignaturePattern

    $state = Invoke-InCMSite -Config $Config -ScriptBlock {
        $result = @{}

        foreach ($application in @(Get-CMApplication)) {
            $xml         = [string]$application.SDMPackageXML
            $fingerprint = ''
            if ($xml -match 'content\s+(?<fp>\d+f/\d+b/\d+)') { $fingerprint = $Matches['fp'] }

            $location = ''
            try {
                $node = ([xml]$xml).SelectSingleNode('//*[local-name()="DeploymentType"]//*[local-name()="Content"]/*[local-name()="Location"]')
                if ($node) { $location = $node.InnerText }
            }
            catch { }

            $result[$application.LocalizedDisplayName] = [pscustomobject]@{
                AppName     = $application.LocalizedDisplayName
                Publisher   = [string]$application.Manufacturer
                Version     = [string]$application.SoftwareVersion
                PackageID   = [string]$application.PackageID
                Origin      = $(if (($xml -match $signature) -or ($xml -match 'Generated by SCCMAppHelper')) { 'this tool' } else { 'foreign' })
                Fingerprint = $fingerprint
                Location    = $location
                Deployments = 0
                Content     = ''
            }
        }

        # One call for all deployments; a failure here leaves the count at zero
        # and says so, rather than taking the whole inventory down.
        try {
            foreach ($deployment in @(Get-CMApplicationDeployment -ErrorAction Stop)) {
                $name = [string]$deployment.ApplicationName
                if ($result.ContainsKey($name)) { $result[$name].Deployments++ }
            }
        }
        catch { Write-Warn ("Could not read the deployments: {0}" -f $_.Exception.Message) }

        # Distribution status per package id: how many distribution points hold
        # the content, are still receiving it, or failed.
        try {
            $byPackage = @{}
            foreach ($status in @(Get-CMDistributionStatus -ErrorAction Stop)) {
                $byPackage[[string]$status.PackageID] = $status
            }
            foreach ($entry in $result.Values) {
                if (-not $entry.PackageID -or -not $byPackage.ContainsKey($entry.PackageID)) { $entry.Content = 'Not distributed'; continue }
                $status = $byPackage[$entry.PackageID]
                $entry.Content =
                    if     ([int]$status.NumberErrors -gt 0)     { 'Error on {0} DP' -f $status.NumberErrors }
                    elseif ([int]$status.NumberInProgress -gt 0) { 'In progress ({0} DP)' -f $status.NumberInProgress }
                    elseif ([int]$status.NumberInstalled -gt 0)  { 'On {0} DP' -f $status.NumberInstalled }
                    elseif ([int]$status.Targeted -gt 0)         { 'Targeted, not there yet' }
                    else                                         { 'Not distributed' }
            }
        }
        catch { Write-Warn ("Could not read the distribution status: {0}" -f $_.Exception.Message) }

        return $result
    }

    return $state
}

<#
    One row per application: definition, package and site joined on the
    application name "<Name> - <Version>". Returns the rows together with
    whether the site could be read and where the packages are.

    Site applications with no definition and no package are listed when this
    tool published them - the folder may have been cleaned away, and the
    application still has to be reachable for retiring. Foreign applications
    without a row or a folder are not: on a grown site they would outnumber
    everything the tool is about.
#>
function Get-AppInventory {
    param(
        $Config = (Get-ActiveConfig),
        [switch]$NoSiteLookup
    )

    $csvPath = Join-Path $rootDir 'Apps.csv'
    Update-AppListSchema -CsvPath $csvPath
    $definitions = @(Import-Csv -LiteralPath $csvPath -Delimiter ';')

    $rows = [ordered]@{}
    $newRow = {
        param($name, $version)
        [pscustomobject]@{
            Name           = $name
            Version        = $version
            Publisher      = ''
            AppFullName    = (Get-AppFullName -Name $name -Version $version)
            HasDefinition  = $false
            Definition     = '-'
            HasPackage     = $false
            Package        = '-'
            PackageRoot    = ''
            ContentPath    = ''
            FilesCount     = 0
            Modified       = $null
            IsPublished    = $false
            Origin         = ''
            SourceChanged  = $false
            Site           = 'Unknown'
            Content        = ''
            Deployments    = ''
            Detail         = ''
            Row            = $null
        }
    }
    $keyOf = { param($name, $version) (Get-AppFullName -Name $name -Version $version).ToLowerInvariant() }

    # --- definitions ---
    foreach ($definition in $definitions) {
        if ([string]::IsNullOrWhiteSpace($definition.Name)) { continue }
        $key = & $keyOf $definition.Name $definition.Version
        if (-not $rows.Contains($key)) { $rows[$key] = & $newRow $definition.Name.Trim() ([string]$definition.Version).Trim() }
        $row = $rows[$key]
        $row.HasDefinition = $true
        $row.Definition    = 'Yes'
        $row.Publisher     = [string]$definition.Publisher
        $row.Row           = $definition
    }

    # --- packages ---
    $workRoot = ''
    $packages = @()
    try {
        $workRoot = Get-PackageWorkRoot -Config $Config
        $packages = @(Get-AppPackage -Config $Config)
    }
    catch { Write-Warn ("The source share is not reachable - only the definitions are listed: {0}" -f $_.Exception.Message) }

    foreach ($package in $packages) {
        $key = & $keyOf $package.AppName $package.AppVersion
        if (-not $rows.Contains($key)) { $rows[$key] = & $newRow $package.AppName $package.AppVersion }
        $row = $rows[$key]
        $row.HasPackage  = $true
        $row.PackageRoot = $package.PackageRoot
        $row.ContentPath = $package.ContentPath
        $row.FilesCount  = $package.FilesCount
        $row.Modified    = $package.LastModified
        $row.Package     = $(if ($package.FilesCount -gt 0) { 'Ready' } else { 'No files' })
        if (-not $row.Publisher) { $row.Publisher = (Read-ADTMetadata -ContentRoot $package.ContentPath).Publisher }
    }

    # --- site ---
    $siteRead = $false
    if (-not $NoSiteLookup) {
        try {
            $state = Get-CMApplicationState -Config $Config
            $siteRead = $true

            foreach ($entry in $state.Values) {
                $parsed = Split-AppFolderName -FolderName $entry.AppName
                $key = & $keyOf $parsed.Name $parsed.Version
                if (-not $rows.Contains($key)) {
                    if ($entry.Origin -ne 'this tool') { continue }
                    $rows[$key] = & $newRow $parsed.Name $parsed.Version
                    if ($entry.Publisher) { $rows[$key].Publisher = $entry.Publisher }
                }
                $row = $rows[$key]
                $row.IsPublished = $true
                $row.Origin      = $entry.Origin
                $row.Content     = $entry.Content
                $row.Deployments = $entry.Deployments

                if ($entry.Origin -ne 'this tool') {
                    $row.Site = 'Foreign'
                }
                elseif ($row.HasPackage -and $entry.Fingerprint) {
                    $current = Get-ContentFingerprint -Path $row.ContentPath
                    $row.SourceChanged = ($current -ne $entry.Fingerprint)
                    $row.Site = $(if ($row.SourceChanged) { 'Published, source changed' } else { 'Published' })
                }
                else {
                    $row.Site = 'Published'
                }
            }
        }
        catch {
            Write-Warn ("Could not read the applications from the site - the site column stays unknown: {0}" -f $_.Exception.Message)
        }
    }

    foreach ($row in $rows.Values) {
        if ($siteRead -and -not $row.IsPublished) { $row.Site = 'Not published' }

        $detail = @()
        $detail += $(if ($row.HasDefinition) { 'Definition: row in Apps.csv' } else { 'Definition: none - the package is imported on publish' })
        $detail += $(if ($row.HasPackage) { 'Package: {0} ({1} file(s) in Files)' -f $row.PackageRoot, $row.FilesCount } else { 'Package: none - build it first' })
        $detail += $(switch ($row.Site) {
            'Published'                 { 'Site: published by this tool, content unchanged since' }
            'Published, source changed' { 'Site: published by this tool, but the package changed since - publish again to send the new content' }
            'Foreign'                   { 'Site: an application of this name exists, but was not created by this tool - publishing overwrites its detection' }
            'Not published'             { 'Site: no application of this name' }
            default                     { 'Site: not read' }
        })
        if ($row.IsPublished) { $detail += ('Content: {0} - Deployments: {1}' -f $row.Content, $row.Deployments) }
        $row.Detail = ($detail -join [Environment]::NewLine)
    }

    return [pscustomobject]@{
        Rows     = @($rows.Values | Sort-Object Name, Version)
        SiteRead = $siteRead
        WorkRoot = $workRoot
    }
}

#endregion

#region ------------------------------------------------------ the definition

<#
    Writes a row into Apps.csv, replacing the row of the same name and version
    if there is one. -ReplaceName / -ReplaceVersion name the row to replace when
    the key itself was edited.
#>
function Set-AppListRow {
    param(
        [Parameter(Mandatory = $true)]$App,
        [string]$ReplaceName,
        [string]$ReplaceVersion,
        [string]$CsvPath = (Join-Path $rootDir 'Apps.csv')
    )

    Update-AppListSchema -CsvPath $CsvPath
    $rows = @(Import-Csv -LiteralPath $CsvPath -Delimiter ';')

    $oldName    = $(if ($ReplaceName)    { $ReplaceName }    else { $App.Name })
    $oldVersion = $(if ($ReplaceVersion) { $ReplaceVersion } else { $App.Version })

    $kept = @($rows | Where-Object {
        -not ($_.Name.Trim() -eq $oldName.Trim() -and ([string]$_.Version).Trim() -eq $oldVersion.Trim()) -and
        -not ($_.Name.Trim() -eq $App.Name.Trim() -and ([string]$_.Version).Trim() -eq $App.Version.Trim())
    })
    $replaced = ($kept.Count -lt $rows.Count)

    $new = New-Object psobject
    foreach ($column in $script:AppListColumns) {
        $value = ''
        if ($App.PSObject.Properties.Name -contains $column) { $value = [string]$App.$column }
        $new | Add-Member -MemberType NoteProperty -Name $column -Value $value
    }

    ($kept + $new) |
        Sort-Object Name, Version |
        Select-Object -Property $script:AppListColumns |
        Export-Csv -LiteralPath $CsvPath -Delimiter ';' -NoTypeInformation -Encoding UTF8

    if ($replaced) { Write-Ok ("App list updated: {0} - {1}" -f $App.Name, $App.Version) }
    else           { Write-Ok ("Added to the app list: {0} - {1}" -f $App.Name, $App.Version) }
}

function Remove-AppListRow {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][string]$Version,
        [string]$CsvPath = (Join-Path $rootDir 'Apps.csv')
    )

    if (-not (Test-Path -LiteralPath $CsvPath)) { return }
    $rows = @(Import-Csv -LiteralPath $CsvPath -Delimiter ';')
    $kept = @($rows | Where-Object { -not ($_.Name.Trim() -eq $Name.Trim() -and ([string]$_.Version).Trim() -eq $Version.Trim()) })
    if ($kept.Count -eq $rows.Count) { return }

    if ($kept.Count -eq 0) {
        Set-Content -LiteralPath $CsvPath -Value ('"' + ($script:AppListColumns -join '";"') + '"') -Encoding UTF8
    }
    else {
        $kept | Sort-Object Name, Version | Select-Object -Property $script:AppListColumns |
            Export-Csv -LiteralPath $CsvPath -Delimiter ';' -NoTypeInformation -Encoding UTF8
    }
    Write-Ok ("Removed from the app list: {0} - {1}" -f $Name, $Version)
}

<#
    An Apps.csv shaped object from whatever carries the columns - a CSV row, an
    inventory row's definition, or the ordered hashtable the editor returns.
#>
function ConvertTo-AppRecord {
    param($Source)

    $app = [pscustomobject]@{
        Publisher        = ''
        Name             = ''
        Version          = ''
        DetectionMethod  = 'Registry'
        DetectionPattern = ''
        ProductCode      = ''
        InstallCmd       = ''
        UninstallCmd     = ''
        Notes            = ''
    }
    if ($null -eq $Source) { return $app }

    foreach ($column in $script:AppListColumns) {
        $value = $null
        if ($Source -is [System.Collections.IDictionary]) { if ($Source.Contains($column)) { $value = $Source[$column] } }
        elseif ($Source.PSObject.Properties.Name -contains $column) { $value = $Source.$column }
        if ($null -ne $value) { $app.$column = [string]$value }
    }
    if ([string]::IsNullOrWhiteSpace($app.DetectionMethod)) { $app.DetectionMethod = 'Registry' }
    return $app
}

<#
    The row for an installer picked from disk - the same reading the From MSI
    and From EXE buttons of the editor do, as a record.
#>
function ConvertTo-FileAppRow {
    param([Parameter(Mandatory = $true)][string]$Path)

    $app = ConvertTo-AppRecord
    $fileName = Split-Path -Leaf $Path

    if ([System.IO.Path]::GetExtension($Path) -eq '.msi') {
        $props = Get-MsiProperties -Path $Path
        $app.Publisher       = [string]$props['Manufacturer']
        $app.Name            = [string]$props['ProductName']
        $app.Version         = [string]$props['ProductVersion']
        $app.ProductCode     = [string]$props['ProductCode']
        $app.DetectionMethod = 'MSI'
        $app.Notes           = "from $fileName"
    }
    else {
        $props = Get-ExeProperties -Path $Path
        $app.Publisher       = [string]$props['Manufacturer']
        $app.Name            = [string]$props['ProductName']
        $app.Version         = [string]$props['ProductVersion']
        $app.DetectionMethod = 'Registry'
        # /S is the NSIS switch and a guess - an EXE does not say which
        # installer built it. The editor says so next to the field.
        $app.InstallCmd      = "Start-ADTProcess -FilePath '$fileName' -ArgumentList '/S'   # /S fits NSIS - check the installer kind"
        $app.Notes           = "from $fileName"
    }

    return $app
}

<#
    Opens the folder and the script of a package the way the old packaging
    assistant did - only wanted when the tool could not put the installer in
    Files itself.
#>
function Open-PackageForEditing {
    param(
        [Parameter(Mandatory = $true)][string]$PackageRoot,
        $Config = (Get-ActiveConfig)
    )

    if (-not ($Config.openExplorerOnCreate -or $Config.openEditorOnCreate)) { return }
    $contentPath = Get-PackageContentPath -PackageRoot $PackageRoot -Config $Config

    if ($Config.openExplorerOnCreate) {
        Write-Host 'ToDo: copy all setup files into .\Files, then press ENTER' -ForegroundColor Cyan
        explorer (Join-Path $contentPath 'Files')
        pause
    }
    if ($Config.openEditorOnCreate) {
        Write-Host 'ToDo: check the Install & Uninstall sections, then press ENTER' -ForegroundColor Cyan
        $editor = if ($Config.editor) { $Config.editor } else { 'notepad' }
        & $editor (Join-Path $contentPath 'Invoke-AppDeployToolkit.ps1')
        pause
    }
}

#endregion

#region ---------------------------------------------------------- the actions

<#
    Adds an application in one step: fetch the installer, confirm the record,
    build the package with the installer in Files, write the row.

        Winget   pick a package from the manifests, download and verify
        File     pick an EXE or MSI that was downloaded separately
        Blank    an empty record - the package is built without an installer
                 and the folder is opened for filling in by hand

    -Template prefills the editor from an existing row, which is what "New
    version" is: the same product, resolved to its newest version.
#>
function Add-AppFromSource {
    param(
        [Parameter(Mandatory = $true)][ValidateSet('Winget', 'File', 'Blank')][string]$Source,
        $Template,
        $Config = (Get-ActiveConfig)
    )

    $app       = ConvertTo-AppRecord -Source $Template
    $installer = $null
    $title     = 'New application'

    switch ($Source) {
        'Winget' {
            $found = Read-CatalogPackage -Config $Config -Template $Template
            if (-not $found) { return $null }
            $winget = $found.Row

            if (-not $Template) { $app = ConvertTo-AppRecord -Source $winget }
            else {
                # A new version of a known product. The name stays - it is what
                # the versions are grouped by and what supersedence follows - and
                # so does a detection somebody has worked out, unless the new
                # installer is an MSI, where the ProductCode is the better rule.
                # Version, commands and notes follow the new installer.
                $app.Version      = $winget.Version
                $app.InstallCmd   = $winget.InstallCmd
                $app.UninstallCmd = $winget.UninstallCmd
                $app.Notes        = $winget.Notes
                if (-not $app.Publisher) { $app.Publisher = $winget.Publisher }
                if ($winget.DetectionMethod -eq 'MSI' -or -not $app.DetectionPattern) {
                    $app.DetectionMethod  = $winget.DetectionMethod
                    $app.DetectionPattern = $winget.DetectionPattern
                    $app.ProductCode      = $winget.ProductCode
                }
            }
            $installer = $found.File
            $title     = 'New application from winget'
        }
        'File' {
            $ofd = New-Object Microsoft.Win32.OpenFileDialog
            $ofd.Title  = 'Select the installer'
            $ofd.Filter = 'Installers (*.msi;*.exe)|*.msi;*.exe|All files (*.*)|*.*'
            if ($ofd.ShowDialog() -ne $true -or -not $ofd.FileName) { Write-Info 'Cancelled.'; return $null }

            $read = ConvertTo-FileAppRow -Path $ofd.FileName
            if (-not $Template) { $app = $read }
            else {
                if ($read.Version) { $app.Version = $read.Version } else { $app.Version = '' }
                $app.InstallCmd   = $read.InstallCmd
                $app.UninstallCmd = $read.UninstallCmd
                $app.Notes        = $read.Notes
                if (-not $app.Publisher) { $app.Publisher = $read.Publisher }
                if ($read.DetectionMethod -eq 'MSI' -or -not $app.DetectionPattern) {
                    $app.DetectionMethod  = $read.DetectionMethod
                    $app.DetectionPattern = $read.DetectionPattern
                    $app.ProductCode      = $read.ProductCode
                }
            }
            $installer = $ofd.FileName
            $title     = 'New application from ' + (Split-Path -Leaf $ofd.FileName)
        }
        'Blank' {
            if ($Template) { $app.Version = '' }
            $title = 'New application'
        }
    }

    $item = [ordered]@{}
    foreach ($column in $script:AppListColumns) { $item[$column] = $app.$column }

    $script:EditDialogInstallerPath = $null
    $answer = Open-EditDialog -item $item -title $title -PropertyOrder $script:AppListColumns
    $answer = $answer | Where-Object { $_ -isnot [int] }
    if (-not $answer) {
        if ($installer -and $installer -like (Join-Path (Get-PackageWorkRoot -Config $Config) '_DL\*')) {
            Write-Info "Cancelled - the download stays in $installer"
        }
        else { Write-Info 'Cancelled.' }
        return $null
    }
    if ($script:EditDialogInstallerPath) { $installer = $script:EditDialogInstallerPath }

    $app = ConvertTo-AppRecord -Source $answer
    if (-not $app.Name -or -not $app.Version) { throw 'Name and Version are required - they name the package folder and the application.' }

    Set-AppListRow -App $app
    $packageRoot = New-AppPackage -App $app -Config $Config -InstallerPath $installer
    if (-not $installer) { Open-PackageForEditing -PackageRoot $packageRoot -Config $Config }
    return $packageRoot
}

<#
    Edits the definition of a row. A package that exists is rebuilt from the
    edited row - metadata and commands, nothing else - so the row stays the
    source of truth. Name and Version are the key: editing them does not rename
    a package folder, and the message says so.
#>
function Edit-AppDefinition {
    param(
        [Parameter(Mandatory = $true)]$InventoryRow,
        $Config = (Get-ActiveConfig)
    )

    $app  = ConvertTo-AppRecord -Source $InventoryRow.Row
    if (-not $InventoryRow.HasDefinition) {
        $app.Name    = $InventoryRow.Name
        $app.Version = $InventoryRow.Version
        $app.Publisher = $InventoryRow.Publisher
    }
    $item = [ordered]@{}
    foreach ($column in $script:AppListColumns) { $item[$column] = $app.$column }

    $script:EditDialogInstallerPath = $null
    $answer = Open-EditDialog -item $item -title ('Edit: ' + $InventoryRow.AppFullName) -PropertyOrder $script:AppListColumns
    $answer = $answer | Where-Object { $_ -isnot [int] }
    if (-not $answer) { Write-Info 'Cancelled.'; return $false }

    $edited = ConvertTo-AppRecord -Source $answer
    if (-not $edited.Name -or -not $edited.Version) { throw 'Name and Version are required.' }

    $keyChanged = ($edited.Name.Trim() -ne $InventoryRow.Name) -or ($edited.Version.Trim() -ne $InventoryRow.Version)
    Set-AppListRow -App $edited -ReplaceName $InventoryRow.Name -ReplaceVersion $InventoryRow.Version

    if ($InventoryRow.HasPackage -and $keyChanged) {
        $null = Show-MessageDialog -Caption 'Definition edited' -Buttons 'OK' -Icon 'Information' -Text (
            "The name or version changed. The package folder`n`n{0}`n`nkeeps its name - Build package creates a new one for `"{1} - {2}`"." -f
            $InventoryRow.PackageRoot, $edited.Name, $edited.Version)
        return $true
    }

    if ($InventoryRow.HasPackage) {
        $null = New-AppPackage -App $edited -Config $Config -InstallerPath $script:EditDialogInstallerPath
    }
    return $true
}

<#
    Removes definitions. The package folder and the application in the site are
    not touched - Retire is for those.
#>
function Remove-AppDefinition {
    param([Parameter(Mandatory = $true)]$InventoryRows)

    $rows = @($InventoryRows | Where-Object { $_.HasDefinition })
    if ($rows.Count -eq 0) {
        $null = Show-MessageDialog -Text 'None of the selected rows has a definition in Apps.csv.' -Caption 'Delete definition' -Buttons 'OK' -Icon 'Information'
        return
    }

    $withPackage = @($rows | Where-Object { $_.HasPackage -or $_.IsPublished }).Count
    $text = "Delete {0} definition(s) from Apps.csv?`n`n{1}" -f $rows.Count, (($rows | ForEach-Object { $_.AppFullName }) -join [Environment]::NewLine)
    if ($withPackage -gt 0) {
        $text += "`n`n{0} of them have a package or an application. Those stay - only the row goes, and the package would be imported again on the next publish." -f $withPackage
    }
    $answer = Show-MessageDialog -Text $text -Caption 'Delete definition' -Buttons 'YesNo' -Icon 'Warning'
    if ($answer -ne 'Yes') { Write-Info 'Cancelled.'; return }

    foreach ($row in $rows) { Remove-AppListRow -Name $row.Name -Version $row.Version }
}

<#
    Builds the packages of the selected rows. A row without a definition but
    with a package is taken over instead - that is what Import-AppPackage does.
#>
function Build-AppPackages {
    param(
        [Parameter(Mandatory = $true)]$InventoryRows,
        $Config = (Get-ActiveConfig)
    )

    $rows = @($InventoryRows)
    foreach ($row in $rows) {
        try {
            if ($row.HasDefinition) {
                $packageRoot = New-AppPackage -App (ConvertTo-AppRecord -Source $row.Row) -Config $Config
                if (-not $row.HasPackage -and $rows.Count -eq 1) { Open-PackageForEditing -PackageRoot $packageRoot -Config $Config }
            }
            elseif ($row.HasPackage) {
                $null = Import-AppPackage -PackageRoot $row.PackageRoot -Bulk:($rows.Count -gt 1) -Config $Config
            }
            else {
                Write-Warn ("[{0}] has neither a definition nor a package - nothing to build." -f $row.AppFullName)
            }
        }
        catch {
            Write-Fail ("[{0}] {1}" -f $row.AppFullName, $_.Exception.Message)
            if ($rows.Count -eq 1) { pause }
        }
    }
}

<#
    Publishes the selected rows. A row without a package cannot be published;
    it is built first when it has a definition, so "publish" on a fresh row does
    the whole way.
#>
function Publish-AppPackages {
    param(
        [Parameter(Mandatory = $true)]$InventoryRows,
        $Config = (Get-ActiveConfig)
    )

    $rows = @($InventoryRows)
    $bulk = ($rows.Count -gt 1)
    foreach ($row in $rows) {
        try {
            $packageRoot = $row.PackageRoot
            if (-not $row.HasPackage) {
                if (-not $row.HasDefinition) { Write-Warn ("[{0}] has no package on the share - nothing to publish." -f $row.AppFullName); continue }
                Write-Info ("[{0}] has no package yet - building it first." -f $row.AppFullName)
                $packageRoot = New-AppPackage -App (ConvertTo-AppRecord -Source $row.Row) -Config $Config
            }
            if ($row.HasPackage -and $row.FilesCount -eq 0) {
                Write-Warn ("[{0}] Files\ is empty - the package installs nothing until the installer is in there." -f $row.AppFullName)
            }
            Publish-CMApplication -PackageRoot $packageRoot -Bulk:$bulk -Config $Config
        }
        catch {
            Write-Fail ("[{0}] {1}" -f $row.AppFullName, $_.Exception.Message)
            if (-not $bulk) { pause }
        }
    }
}

<#
    Runs the action the main dialog returned. Returns $false when the tool
    should exit, $true to show the list again.
#>
function Invoke-InventoryAction {
    param(
        [Parameter(Mandatory = $true)]$Choice,
        $Config = (Get-ActiveConfig)
    )

    $selection = @($Choice.Selection)
    $first     = $selection | Select-Object -First 1

    switch ($Choice.Action) {
        'Add' {
            Write-Step ("Add application from {0}" -f $Choice.Source.ToLower())
            try { $null = Add-AppFromSource -Source $Choice.Source -Config $Config }
            catch { Write-Fail $_.Exception.Message; pause }
        }
        'NewVersion' {
            if (-not $first) { break }
            Write-Step ("New version of {0}" -f $first.Name)
            try { $null = Add-AppFromSource -Source $Choice.Source -Template (ConvertTo-AppRecord -Source $(if ($first.Row) { $first.Row } else { $first })) -Config $Config }
            catch { Write-Fail $_.Exception.Message; pause }
        }
        'Edit' {
            if (-not $first) { break }
            Write-Step ("Edit {0}" -f $first.AppFullName)
            try { $null = Edit-AppDefinition -InventoryRow $first -Config $Config }
            catch { Write-Fail $_.Exception.Message; pause }
        }
        'Delete' {
            if ($selection.Count -eq 0) { break }
            Write-Step 'Delete definition'
            Remove-AppDefinition -InventoryRows $selection
        }
        'Build' {
            if ($selection.Count -eq 0) { break }
            Write-Step 'Build packages'
            Build-AppPackages -InventoryRows $selection -Config $Config
        }
        'Publish' {
            if ($selection.Count -eq 0) { break }
            Write-Step 'Publish to ConfigMgr'
            Publish-AppPackages -InventoryRows $selection -Config $Config
        }
        'Retire' {
            Write-Step 'Retire applications'
            retireApps
        }
        'OpenFolder' {
            try {
                $path = $(if ($first -and $first.HasPackage) { $first.PackageRoot } else { Get-PackageWorkRoot -Config $Config })
                Write-Info "Opening $path"
                explorer $path
            }
            catch { Write-Warn $_.Exception.Message }
        }
        'Tools'   { Write-Step 'Tools'; Show-ToolsMenu }
        'Refresh' { }
        'Cancel'  { Write-Info 'Closed';          return $false }
        'Closed'  { Write-Info 'Closed with [X]'; return $false }
        default   { Write-Info "Unexpected: $($Choice.Action)"; return $false }
    }
    return $true
}

#endregion
