<#
.SYNOPSIS
    Publishes this package as a ConfigMgr application.

.DESCRIPTION
    Generated by SCCMAppHelper #TOOLVER# for: #APP#

    The script is deliberately thin - all logic lives in the tool's
    Publish-CMApplication, so improvements and fixes also reach packages that
    were created with an earlier version of the tool. The package metadata is
    read from .\package.json.

.PARAMETER bulk
    Suppresses interactive questions (used when several packages are published
    in a row).
#>
param(
    [switch]$bulk
)

$rootDir     = '#ROOT#'
$toolVersion = '#TOOLVER#'

$functionsPath = Join-Path $rootDir 'Functions\functions.ps1'
if (-not (Test-Path -LiteralPath $functionsPath)) {
    throw "SCCMAppHelper was not found at [$rootDir]. Adjust `$rootDir at the top of this script."
}

. $functionsPath

$packageRoot = Split-Path -Parent $PSScriptRoot

try {
    Publish-CMApplication -PackageRoot $packageRoot -Bulk:$bulk
}
catch {
    Write-Fail $_.Exception.Message
    if (-not $bulk) { pause }
}
