<#
.SYNOPSIS
    ConfigMgr script detection - registry / Add-Remove-Programs based.

.DESCRIPTION
    Detects an application by its DisplayName in the uninstall registry hives and
    compares the installed DisplayVersion against a target version.

    ConfigMgr script detection contract:
        exit code 0 + any STDOUT output   -> application IS installed
        exit code 0 + no STDOUT output    -> application is NOT installed
        exit code <> 0                    -> detection failed (error state)

    Never write to STDOUT unless the application really is detected.

.NOTES
    Generated by SCCMAppHelper #TOOLVER# - https://blog.zarenko.net
#>

$AppName       = '#DN#'
$SearchPattern = '#PATTERN#'
$TargetVersion = '#VER#'
$LogPath       = '#LOGPATH#'

$logFile = Join-Path $LogPath ("Detect_{0}.log" -f ($AppName -replace '[\\/:*?"<>|]', '_'))

function Write-DetectLog {
    param([string]$Message)
    try {
        if (-not (Test-Path -LiteralPath $LogPath)) { New-Item -ItemType Directory -Path $LogPath -Force | Out-Null }
        Add-Content -LiteralPath $logFile -Value ("{0}`t{1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message) -ErrorAction SilentlyContinue
    } catch { }
}

$registryPaths = @(
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall',
    'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall',
    'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'
)

try {
    Write-DetectLog ("Detecting [{0}] pattern [{1}] target version [{2}]" -f $AppName, $SearchPattern, $TargetVersion)

    $found = @()
    foreach ($registryPath in $registryPaths) {
        $items = Get-ChildItem -Path $registryPath -ErrorAction SilentlyContinue
        foreach ($item in $items) {
            $props = Get-ItemProperty -Path $item.PSPath -ErrorAction SilentlyContinue
            if ($props.DisplayName -like $SearchPattern) { $found += $props }
        }
    }

    if ($found.Count -eq 0) {
        Write-DetectLog 'Not installed - no matching DisplayName found.'
        exit 0
    }

    # Compare versions. Prefer a real [version] comparison, fall back to string
    # equality for products that do not use a parsable version (e.g. "19c").
    $targetParsed = $null
    $isTargetParsable = [System.Version]::TryParse($TargetVersion, [ref]$targetParsed)

    foreach ($entry in $found) {
        $installedVersion = $entry.DisplayVersion
        Write-DetectLog ("Candidate: [{0}] version [{1}]" -f $entry.DisplayName, $installedVersion)

        if ($isTargetParsable) {
            $installedParsed = $null
            if ([System.Version]::TryParse($installedVersion, [ref]$installedParsed)) {
                if ($installedParsed -ge $targetParsed) {
                    Write-DetectLog ("Installed - {0} >= {1}" -f $installedParsed, $targetParsed)
                    Write-Output 'Installed'
                    exit 0
                }
            }
        }
        elseif ($installedVersion -eq $TargetVersion) {
            Write-DetectLog 'Installed - version string matches.'
            Write-Output 'Installed'
            exit 0
        }
    }

    Write-DetectLog 'Not installed - only older / non-matching versions present.'
    exit 0
}
catch {
    Write-DetectLog ("Detection error: {0}" -f $_.Exception.Message)
    exit 1
}
