<#
.SYNOPSIS
    ConfigMgr script detection - file version based.

.DESCRIPTION
    Detects an application by the presence of a file and, if a target version is
    given, by comparing the file version against it.

    ConfigMgr script detection contract:
        exit code 0 + any STDOUT output   -> application IS installed
        exit code 0 + no STDOUT output    -> application is NOT installed
        exit code <> 0                    -> detection failed (error state)

.NOTES
    Generated by SCCMAppHelper #TOOLVER# - https://blog.zarenko.net
#>

$AppName       = '#DN#'
$FilePath      = '#FILEPATH#'
$TargetVersion = '#VER#'
$LogPath       = '#LOGPATH#'

$logFile = Join-Path $LogPath ("Detect_{0}.log" -f ($AppName -replace '[\\/:*?"<>|]', '_'))

function Write-DetectLog {
    param([string]$Message)
    try {
        if (-not (Test-Path -LiteralPath $LogPath)) { New-Item -ItemType Directory -Path $LogPath -Force | Out-Null }
        Add-Content -LiteralPath $logFile -Value ("{0}`t{1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message) -ErrorAction SilentlyContinue
    } catch { }
}

try {
    Write-DetectLog ("Detecting [{0}] file [{1}]" -f $AppName, $FilePath)

    $expanded = [System.Environment]::ExpandEnvironmentVariables($FilePath)

    if (-not (Test-Path -LiteralPath $expanded)) {
        Write-DetectLog 'Not installed - file not found.'
        exit 0
    }

    if ([string]::IsNullOrWhiteSpace($TargetVersion)) {
        Write-DetectLog 'Installed - file present (no version check).'
        Write-Output 'Installed'
        exit 0
    }

    $fileVersion = (Get-Item -LiteralPath $expanded).VersionInfo.FileVersion
    Write-DetectLog ("File version: [{0}]" -f $fileVersion)

    $targetParsed = $null
    $installedParsed = $null
    $normalized = ($fileVersion -replace ',', '.') -replace '\s', ''
    if ([System.Version]::TryParse($TargetVersion, [ref]$targetParsed) -and
        [System.Version]::TryParse($normalized, [ref]$installedParsed)) {
        if ($installedParsed -ge $targetParsed) {
            Write-DetectLog ("Installed - {0} >= {1}" -f $installedParsed, $targetParsed)
            Write-Output 'Installed'
            exit 0
        }
        Write-DetectLog ("Not installed - {0} < {1}" -f $installedParsed, $targetParsed)
        exit 0
    }

    if ($fileVersion -eq $TargetVersion) {
        Write-DetectLog 'Installed - file version string matches.'
        Write-Output 'Installed'
        exit 0
    }

    Write-DetectLog 'Not installed - file version does not match.'
    exit 0
}
catch {
    Write-DetectLog ("Detection error: {0}" -f $_.Exception.Message)
    exit 1
}
