<#
.SYNOPSIS
    ConfigMgr script detection - MSI ProductCode based.

.DESCRIPTION
    Detects an application by its MSI ProductCode. Optionally also compares the
    installed DisplayVersion, which catches minor-upgrade MSIs that keep the
    same ProductCode.

    ConfigMgr script detection contract:
        exit code 0 + any STDOUT output   -> application IS installed
        exit code 0 + no STDOUT output    -> application is NOT installed
        exit code <> 0                    -> detection failed (error state)

.NOTES
    Generated by SCCMAppHelper #TOOLVER# - https://blog.zarenko.net
#>

$AppName       = '#DN#'
$ProductCode   = '#PRODUCTCODE#'
$TargetVersion = '#VER#'
$LogPath       = '#LOGPATH#'

$logFile = Join-Path $LogPath ("Detect_{0}.log" -f ($AppName -replace '[\\/:*?"<>|]', '_'))

function Write-DetectLog {
    param([string]$Message)
    try {
        if (-not (Test-Path -LiteralPath $LogPath)) { New-Item -ItemType Directory -Path $LogPath -Force | Out-Null }
        Add-Content -LiteralPath $logFile -Value ("{0}`t{1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message) -ErrorAction SilentlyContinue
    } catch { }
}

try {
    Write-DetectLog ("Detecting [{0}] ProductCode [{1}]" -f $AppName, $ProductCode)

    $keys = @(
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$ProductCode",
        "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\$ProductCode",
        "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$ProductCode"
    )

    $entry = $null
    foreach ($key in $keys) {
        $entry = Get-ItemProperty -Path $key -ErrorAction SilentlyContinue
        if ($entry) { break }
    }

    if (-not $entry) {
        Write-DetectLog 'Not installed - ProductCode not registered.'
        exit 0
    }

    if ([string]::IsNullOrWhiteSpace($TargetVersion)) {
        Write-DetectLog 'Installed - ProductCode present (no version check).'
        Write-Output 'Installed'
        exit 0
    }

    $targetParsed = $null
    $installedParsed = $null
    if ([System.Version]::TryParse($TargetVersion, [ref]$targetParsed) -and
        [System.Version]::TryParse($entry.DisplayVersion, [ref]$installedParsed)) {
        if ($installedParsed -ge $targetParsed) {
            Write-DetectLog ("Installed - {0} >= {1}" -f $installedParsed, $targetParsed)
            Write-Output 'Installed'
            exit 0
        }
        Write-DetectLog ("Not installed - {0} < {1}" -f $installedParsed, $targetParsed)
        exit 0
    }

    # Versions not parsable - ProductCode presence is authoritative.
    Write-DetectLog 'Installed - ProductCode present, version not comparable.'
    Write-Output 'Installed'
    exit 0
}
catch {
    Write-DetectLog ("Detection error: {0}" -f $_.Exception.Message)
    exit 1
}
